---
- name: 앤서블 깃클론, 업데이트
  hosts: centos
  become: yes
  vars:
    git_repo_url: "https://github.com/shvic100/ansiblelab3.git"
    web_server_root: "/var/www/html/ansiblelab3"  # 웹 서버의 기본 디렉토리
  
  tasks:
    - name: centos git
      action: "{{ ansible_pkg_mgr }} name=git state=present"
    
    - name: stop firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no      

    - name: clone update repo
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ web_server_root }}"
        version: master
        update: yes
      become: yes
      register: git_result

    - name: permission
      file:
        path: "{{ web_server_root }}"
        state: directory
        recurse: yes
        owner: vagrant
        group: vagrant
      become: yes


    - name: httpd restart를 위한 trigger set
      ansible.builtin.set_fact:
        restart_httpd: true
      when: git_result.changed

  handlers:
    - name: restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted
      when: restart_httpd
      listen: git_result

    - name: result
      ansible.builtin.debug:
        var: git_result






  

